### ISSUE TITLE
이슈생성화면의 Assignee, Label, Milestone 팝업 구현

### ISSUE THREAD

**Issue by ed-jinyoung-park** [boostcamp-2020/IssueTracker-14#196]
- [x] Assignees 부분을 클릭하면 담당자 목록 팝업이 뜨고 선택할 수 있다. 담당자 목록에서 담당자를 선택하면 No one 텍스트가 다음과 같이 할당된 담당자로 변경된다.
- [x] assign yourself 텍스트를 클릭하면 바로 No one 텍스트가 없어지고 본인이 담당자로 할당된다.

- [x] Labels 부분을 클릭하면 레이블 목록 팝업이 뜨고 선택할 수 있다. 레이블 목록에서 레이블을 선택하면 None yet 텍스트가 다음과 같이 어떤 레이블이 선택됐는지를 알 수 있도록 변경된다.

- [x] Milestone 부분을 클릭하면 마일스톤 목록 팝업이 뜨고 선택할 수 있다. 마일스톤 목록에서 마일스톤을 선택하면 No milestone 텍스트가 다음과 같이 어떤 마일스톤을 선택했는지를 알 수 있도록 변경된다.
